### PR TITLE
Update to 1.8, Still need to add rabbits to Animals

### PR DESCRIPTION
**Pull request by DrkMatr1984**

### CODE REVIEW

**Comment by cgokmen** [comment]
I will review both commits tomorrow and merge the pull request if everything's alright (probably is)

I've been away from the MC community for a while now so I'll have to update first :)

**Comment by DrkMatr1984** [comment]
Ok, it's fine ;) I've been using it on my server with no issues. If you need 1.8 stuff check out my DropBox here :
https://www.dropbox.com/sh/s3zwqpmsubj92rv/AAArUso3TDdhG3kJFKsnX3xIa?dl=0

**Comment by cgokmen** [comment]
Hey, I can give you contributor status on this project if you want. I'm busy IRL with a few more projects and it may take up to a couple months before I can focus on my Minecraft work!

**Comment by DrkMatr1984** [comment]
That's fine. I can keep the project maintained and updated on Bukkit for the users.

**Pull request merged**
