### PR TITLE
Update for 1.8.7/1.8.8

### PR DESCRIPTION
**Pull request by DrkMatr1984**

### CODE REVIEW

**Comment by cgokmen** [comment]
Thank you! I have added you as a contributor so you can just merge your commits directly.

**Comment by DrkMatr1984** [comment]
Np! I also released your plugin on Spigot :) Check out the Spigot page if you like!

**Comment by cgokmen** [comment]
I actually did that before, but md5 thought it was "offensive" and had it removed. What a jerk.

**Comment by DrkMatr1984** [comment]
lmao, Well, he didn't notice this time yet ;) So we'll see. Still getting downloads and I still use this plugin on my RPG server to keep the animal populations up.

**Pull request merged**
